from fastapi import APIRouter, Depends, Header
from pydantic import BaseModel
from sqlalchemy.orm import Session
from db.session import get_db
from graph_reasoning.traversal import load_full_graph, traverse_graph
from agents.query_simulation_agent import QuerySimulationAgent

router = APIRouter(tags=["Query"])
agent = QuerySimulationAgent()


class QueryRequest(BaseModel):
    question: str
    entity_type: str | None = None
    entity_id: int | None = None


@router.post("/query")
def query_digital_twin(req: QueryRequest, db: Session = Depends(get_db), x_llm_api_key: str | None = Header(None)):
    G = load_full_graph(db)

    # Check if a strategy has actually been generated by looking for value chain stages
    has_strategy = any(attr.get('type') == 'value_chain_stage' for _, attr in G.nodes(data=True))

    if not has_strategy:
        return {
            "question": req.question,
            "answer": "There is no strategy generated yet. Please generate a strategy first so I can traverse your Digital Twin!",
            "graph_context": {},
        }

    if req.entity_type and req.entity_id:
        graph_ctx = traverse_graph(G, req.entity_type, req.entity_id, depth=2)
    else:
        # Full graph summary context
        graph_ctx = {
            "node_count": len(G.nodes),
            "edge_count": len(G.edges),
            "sample_nodes": [{"id": n, **G.nodes[n]} for n in list(G.nodes)[:10]],
        }

    answer = agent.answer_query(req.question, graph_ctx, api_key=x_llm_api_key or "")

    return {
        "question": req.question,
        "answer": answer,
        "graph_context": graph_ctx,
    }
